apiVersion: v1
kind: Namespace
metadata:
  name: deepsea
spec: {}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: deepsea-simulator
  namespace: deepsea
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deepsea-simulator-role
rules:
  - apiGroups: ["things.kubecon.io", "deepsea.kubecon.io"]
    resources: ["devices", "modules"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deepsea-simulator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deepsea-simulator-role
subjects:
  - kind: ServiceAccount
    name: deepsea-simulator
    namespace: deepsea
---
apiVersion: v1
kind: Service
metadata:
  name: deepsea-simulator-service
  namespace: deepsea
spec:
  selector:
    app: deepsea-simulator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-deployment
  namespace: deepsea
  labels:
    app: deepsea-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepsea-simulator
  template:
    metadata:
      labels:
        app: deepsea-simulator
    spec:
      serviceAccountName: deepsea-simulator
      containers:
        - name: deapsea-simulator-container
          image: gcr.io/jpbetz-public-images/deepsea-simulator@sha256:cdc9ee4e0ff56e00aa810539ee8dc9010aef14652ac27edd0fa1d13076f0e58b
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
