apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controllers-role
rules:
  - apiGroups: ["things.kubecon.io", "deepsea.kubecon.io"]
    resources: ["devices", "modules"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]