apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simulator-replicaset
  labels:
    app: deepsea-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepsea-simulator
  template:
    metadata:
      labels:
        app: deepsea-simulator
    spec:
      containers:
        - name: deapsea-simulator-container
          image: gcr.io/jpbetz-public-images/deepsea-simulator:latest
          ports:
            - containerPort: 8085