apiVersion: v1
kind: Namespace
metadata:
  name: deepsea
spec: {}
---
apiVersion: v1
kind: Service
metadata:
  name: admission-webhook
  namespace: deepsea
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    webhook: "true"
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: admission-webhook
  namespace: deepsea
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devices.thing.kubecon.com-reader
rules:
- apiGroups: ["things.kubecon.com"]
  resources: ["devices"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deepsea-admission-webhook-devices.thing.kubecon.com-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devices.thing.kubecon.com-reader
subjects:
- kind: ServiceAccount
  name: admission-webhook
  namespace: deepsea
---
apiVersion: v1
kind: Secret
metadata:
  name: admission-serving-cert
  namespace: deepsea
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUV6RENDQXJRQ0NRRFlxNDlWeVZoVGZqQU5CZ2txaGtpRzl3MEJBUXNGQURBb01TWXdKQVlEVlFRRERCMWgKWkcxcGMzTnBiMjR0ZDJWaWFHOXZheTVrWldWd2MyVmhMbk4yWXpBZUZ3MHhPVEV4TURNeE5ERXpNVEZhRncweQpNREV4TURJeE5ERXpNVEZhTUNneEpqQWtCZ05WQkFNTUhXRmtiV2x6YzJsdmJpMTNaV0pvYjI5ckxtUmxaWEJ6ClpXRXVjM1pqTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUF5bzUrUEVxeG1ybkwKTFhpVmZFcG9qRFJBNS85b0VxYU5kU1ZrRklnYnpvZndqbUZWTEpTQ2x4MmRycWtSWTFWWnBIWjBzSTNGcUNCYwpGRkdVVUNBSEpDK1IzU3V0ckVVOHEvRnpUSUZxNmhodUNEdE5XUEdTQW9hWDlYR2RZZGhWOWE3WGhBR3lnbHRCCklBS1lWK3pHc01NRjgzSDE1UUFRaVRmRStjYXNiMGxuUk9acDRlOTIyWDN2R2dMMUJidmUveWVCQThFZTQ2OTAKZ0JmL25Ga2VzTmlJbHg1aVA3WXBxa2UyWk5saFJ2c20rcXJqS3hoMi9OZEFvMjJYU0x5ZTN3Y0NYOGJYTnY2OQpIbEllOUs5RmxwUTM4ZHhickJ0ajltcG56dzZ3MEV1aDBmczVsb1FEWUxIS21tYXJiQnVFT3FYanJCbW1QdkYzCmtPY3c4aG45RUF6VklwQVhpMERMMG5iVDVOMU1HWTYyQ1MxaXUvWWdDSXJkamRWRTB2NGc4MWtXM3FqSHZDN2wKbktCeUZ4Tk9yV2JKbXAyMzhMOUc5YTZON2pyV3R4VENtdVBrSTBjQXlQKzRpL2N5QW1CODBMNWZtTU1BNHVCZgpLZkR3SkUrQm9WK2RtdXA5ZExGTUR4dFYzTGJrZ1BaRnZxQ1hiTDBvcEgrcEFZQTRGYlQ4NXhFdnMwdTc2K0pUCko3bERiMHVOTU83K21QK1RyWTVXaUFlS2wvTUtQdjNCVGwwalY5WlpsajEwU0Ficlgvalk4ZHhNYTdqZXVPckQKVlJxTFlTeEVJdjF3YjN6ZnhqalNySTkwSEx3R2tBdVBwdFVQWHpHVDJ3UkVydHNQV25sZEY3bXNjL1JqRVdmZgo3d3RKQTZhQUFmVzVMbytHUHM3ckRWUHdRaURGV1M4Q0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBZ0VBCldldWNMdUo3TXJROWRNcEZXOWNvWm5Cc3pkeFpEcUJKZFZqQTNDUEV3dmFUdjVpNlhLNnJkbzk5QnVTZWtBN0cKMzRFOFlBZ3NWVWpQQlRWUWNGajJOenZnaTM3RUZ3M0VYN1ZqaklIc2FsazFEald6Yk44UGwrY2ZNOTN2ZGw0SAozUzdlMUNzQzRPTnQyYlBiZzQxTUZwd0k5djdKN0Rpa1ExVzBlNjdZRlBhMzQxRFFrNjZBaWhxTUxZeUwzcE10CmIrdCttNmtFNzNHWUFwMm5EbmErekVZZVZmd1RyUmw1ZmZRSGRhOG9TWVNSQjdFSlk3S3BoRkJaNk0wcUhwT28KUk5zYVVTQXV5WDZhS0lTdkViVmt3NlR2dW52MzVxZmpWSmo5cnkxd212YVh3a0xyTWo4eU95Y044MjVmb3dzRQo3Z0owemJXczBJTTVKMllVSFJDNEpZTHcwS1k0YndWdnlqcUllUzQ4RW5DdkMzRFkzK0xiM01kTTRuOXNwQjVICndrVUhWejhhSVJqNzdEbVpyY21oU1doZGxKVmpuMkhDOUlNMHA2ZFkwMTZWSmhxUVF0WEw2N2tvdU5oQVJIRnEKNC9QWnBMODk0d2VtZk5GNnNRL3hIZE96U3NRbEtKQWF5WTk2WkRQeWMvVGRCdEtmckxwRDRKa0FRM21FY2YwcgpEOHpJZ1hmK2pBNXdWTGFSL3ZlaDFWTkVBY0NpbzloOTF6WEJjTXl5V0FDLzF4dXBwd2hOV3VQMjFhUjJ0cGVTCmNBNVZrd042RlA5cGhLSVF6VlU1V2dQWUJyVklLcXc5azFBV2I1RHRPMmxwYXJWeDMrYkFJRVB4SnJBWE1GeFQKTzQ4RVZkVjVLN2RUeUUxeU81QjMwbVRSUlFNWm9TMC9FcHcrRjlvSm5LMD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQ1N3d2dna29BZ0VBQW9JQ0FRREtqbjQ4U3JHYXVjc3QKZUpWOFNtaU1ORURuLzJnU3BvMTFKV1FVaUJ2T2gvQ09ZVlVzbElLWEhaMnVxUkZqVlZta2RuU3dqY1dvSUZ3VQpVWlJRSUFja0w1SGRLNjJzUlR5cjhYTk1nV3JxR0c0SU8wMVk4WklDaHBmMWNaMWgyRlgxcnRlRUFiS0NXMEVnCkFwaFg3TWF3d3dYemNmWGxBQkNKTjhUNXhxeHZTV2RFNW1uaDczYlpmZThhQXZVRnU5Ny9KNEVEd1I3anIzU0EKRi8rY1dSNncySWlYSG1JL3RpbXFSN1prMldGRyt5YjZxdU1yR0hiODEwQ2piWmRJdko3ZkJ3SmZ4dGMyL3IwZQpVaDcwcjBXV2xEZngzRnVzRzJQMmFtZlBEckRRUzZIUit6bVdoQU5nc2NxYVpxdHNHNFE2cGVPc0dhWSs4WGVRCjV6RHlHZjBRRE5VaWtCZUxRTXZTZHRQazNVd1pqcllKTFdLNzlpQUlpdDJOMVVUUy9pRHpXUmJlcU1lOEx1V2MKb0hJWEUwNnRac21hbmJmd3YwYjFybzN1T3RhM0ZNS2E0K1FqUndESS83aUw5eklDWUh6UXZsK1l3d0RpNEY4cAo4UEFrVDRHaFg1MmE2bjEwc1V3UEcxWGN0dVNBOWtXK29KZHN2U2lrZjZrQmdEZ1Z0UHpuRVMrelM3dnI0bE1uCnVVTnZTNDB3N3Y2WS81T3RqbGFJQjRxWDh3bysvY0ZPWFNOWDFsbVdQWFJJQnV0ZitOangzRXhydU42NDZzTlYKR290aExFUWkvWEJ2Zk4vR09OS3NqM1FjdkFhUUM0K20xUTlmTVpQYkJFU3UydzlhZVYwWHVheHo5R01SWjkvdgpDMGtEcG9BQjlia3VqNFkrenVzTlUvQkNJTVZaTHdJREFRQUJBb0lDQUVrYUMrenVlQktESXhTU0JFRUxDWmd2Cjg0ekczR1IrdjJhYnkvYXMrSHdkQzNBWEtJb2lQczhTM1NsLzBzcXFydU52N01VYkpVNTcvejlHQWVTNDZscmcKNEIrVjkrUElTUkUwM291cDJWQUs2UXNIZSs2eG9DUlJOdDVaMXBiTllKaCtOVUZxNjJXb1VXU2dDeU1RVE5UVwpUWHVDa1YvSUdpK3JkT2RBRUZOSmhuK1RPSHRWMU9yQlRGMXkyOExwL3B6UFFQeDk0Z3dCOG1XWVE2UEZkaElVCjA1YldYRmJxQXpkMUVocHJhWFFZaUFUSFQ1enFBMmRVdC90RFBlbitTTWZzMjZwOU5JYWdnTmhFZ3UrRG9mV3EKSUZhbFZHQlVza3JvTS9iQ01vVzZCZmltVmk1QURvZ0RJajkrOWpiWjUyclRHOHVzcGhicFJtR0JUbVRSaEVaMgpNazZocHh3VEV3dEpPV0pOcHRZekRHc2h1MzZ4c0tYSFVqY0IwZmkvODRlWVlEamlHbzlhYmw3YStqeVQxaGJJCkV6QU4zK3JsdHdveXJGanhJZ09uWVcyOFJpb2VZdGpSYlo2TFV4NkwyWXdLV2MxMCtWaE0velhtTTVCNFNrV2sKTXpKalJSS2tUSGQ0bkNMYVovcFlrQS9YZFpoTlIvNXN0M3MrYWZlRm5pbGkwc1piOWF6S3ZRQ281YkJkdkVBVgpLdGVEVlBLZlpOMVJ2bjZTUDMzdGlWR0NSTXUwNXZZdldkeXgzSEhUNVFydTFvcExzNk1Ia1dMR21pTlg2aW05CmFZVGhGd1VFOWYzMmU1bXlHbDVQYUcxc3dhcGk3WEY4RndUZnIydE4zUWpQRm5oOGN2RmhSZ2pIbk9URCtZcTUKQ3JYWnh4N1d4TDhKY2U4T2h4Q0JBb0lCQVFEcENYdUExTnVPNHQ5c0ZHRENYQVV4b2RjdVdpS3FOZWNoM3FiMwo1a0Z2ZWlkMVEzUjcvQUEzUVhMRFlaU0tKaHlMUXRlYzJBZjgrSUFCUXZ6MjFuQ0YrSjlGaDk2SWduZ0VNRDFpCkk1cXlUaEk0VGJiSFFtNG9Ib1Zta1dUWW5lTVBFMzJsaUVMaExIcVBjalhOYVJyemI0QTErTVpXR3BEZ29wSVgKaXgxdExDc2FUOVhneVg5YmcrVld5K20wYWhSaWdpd3hMMHExTTIxajFldmhoRU9Lc2dpbnQ3YXFXOENVVFNIdwpCcHo3Q01JUXNWS0dCQnZSQ3d4RUd0aS9zenAzaWc1ZVR0VXNIUDI5d05lRTZVN0sxdWFwcHlwdlNiQ2tLdmlYClFJbmRxWUxoTHRZcEd2TU4xMllIbHEzSU0wdDlTKzhnT1I2aEgzdk1qNmUwV2ptZkFvSUJBUURlaEI4SFo4VmMKb1NSRHpZeHRuaXNIaTBaU1FxYnI1UWNMVG42OXdQNElRemxoOGNzM1IzUTN2ZDNTNi9sbVhUb1NjaHZnR2Q5QwpoZ3o0OGFGVC9PNzFRVlZra0QwL2l5N3pQS0RyQldFbmN3VlByQTVxcldKV2FaRmpteEpKeWxvYXdqMDh2TmtMClp6RVdaSFZ4T1FVY3ZvT2JMamVKcE4vVlZzcERiZW1GaVBaODNuZDVHcGZSQ2theGlsZGJyKzI3YmNpOWRZSnoKRGV6a2J0VzFyR3ovNTVUbUR2VkdTU0l1SnlYMmFSS21TTHNwVW9aUjFQU3hsNTE2ZU9rMVRsaktSUlV5TGYyeApHLy9SWVZyNVZSbXBtQzhwNXM3c2pBTU1KYWFiTjFhdFhLa2JMQUxQeWw4cFB6R2c0VytJVmRHV2kwNWR0cFdTCnJQdXB2aDBmMmRaeEFvSUJBRVVWOTVSQkJubzh6aW0zZk53QjlkUTUrNVlWU0xPWFdWZFVMOEhNZEZlOUtoZDgKa1ByMHdZZWdFb3JUMGZxR3crMlJPbVNZTXY0UEdidkdCVUtVWGpXSmVJWmZlbHlUK1VxY2xvWVNzaGpzUmtDRQo0WXYvS0xNaUlVQkFHRnFUckMzYkJHUGZtcHd3MklEUVJoMEliT0lBaTB6MDNLL0lIbTFLSk85djRhQnMrTFpMCk5zZjJWSmhuNk1Tcm5UUk1RcERWc0k1QVMvQ2VOMjdpaTVTRzVwTW1wcVE2TmFBWnBXVVIzTjdReHhjeENIOTAKWWxleXZpQmlHeGZSc2JKYlN4a0hSNjB6eDhUVkwzQml6RUh0L05ycmpPUjgxM3E0cVBKeWZ0SXdZdTdoQXhrSgpEcHFQRDhGcHV5akN4ZkJWTEtzUHFPdXZvMkgyK0hlem11OC8xRmNDZ2dFQVhnTUNQUlc1eS9ZRkpXUnR4VTZECkxZL0phUzNoNmw1OFNHbWtvTFV1WHYxUC9ESzFRaWk5VUdPMm1jdTdObVdEQ0pJUGR2SlhZbnJTZGtkWWV1eXQKWlE5eWJhZUhTUmFjQW9hR0VtWFdjMTFrVEJJTWtVT3AvWXBpcyt1cm9XT09DQ295eHp1ZWsvUElTSWF2RytRVQpaZDJVS3ZjdTNjZThEaDI2SFIwT0FhNHBQZjZjQ1oyVHNPMGZpeGxBNldyK0RTZElIY3ZORHFFK2loRE4yQkQrCmlHd21lOENzSGtMOTN2UUpWUDkxc3EyZDdjcUJGNGZhemtHWmRrb3BkYTBoVkd3MWxWcmJDWDRqNmltd3p4RUcKWTZINW8wRnlBWHp5T0txYnBvNk4zM2I3dDVBenErajdwYWllWmpONDlPZ1ZRZjZmWUhhbzRTeVdzMU93YUdtWAo4UUtDQVFFQXI3ZWc1SnFCamFhYi9seEd6L0xSZDZwSktZS0hhNEsvTUZmbWJySFpNWlQrOXpYTXBuV0ttTEhMCmZBSlVvSzJuenlkK05jYVB5bGZGSGdoa2xkSVVJMkJLMy9lMHljdWFFZDZqUWtqeS84eXpWS0RhK21jQmFrczMKRXI4dGI4T20vb2VUYlFMSkpnVFVqblFQTWlzZ0JtSkhzYkhIU1N4c1FVam5WRWwydzdleFN3ZUdVMUZaT0JyUwpESUErT0E5aVREbW5CRXBkcjhNZFBobXpIZVFyT2M0eEtyR0F2VEtqTkJ2SFRJQW5PT1FlNWQ1NFd1ZEJGTk40ClFxYWkyd2k2Y0N6ZFhKaS8rUTBQN3BGdXZTbHhRcnhxRVNHTGp2R2Q2N09iZjdCdHArelZKcnU4a0dqMW9VNUIKWVZpRkQxR1FPcVAvcHc1Sm9FeGNjL1MvODViQ0pBPT0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-webhook
  namespace: deepsea
  labels:
    webhook: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      webhook: "true"
  template:
    metadata:
      labels:
        webhook: "true"
    spec:
      serviceAccountName: admission-webhook
      containers:
      - name: webhook
        image: docker.io/sttts/deepsea-admission-webhook@sha256:c7bbaa57f4557f06d3d19fc1a7f2d87baaaba3ce61b65c17074e9bb5d861eacd
        imagePullPolicy: Always
        command: ["/admission-webhook"]
        args:
        - --cert-dir=/tmp/certs
        - --secure-port=8443
        - --tls-cert-file=/var/run/webhook/serving-cert/tls.crt
        - --tls-private-key-file=/var/run/webhook/serving-cert/tls.key
        - --v=4
        volumeMounts:
        - name: serving-cert
          readOnly: true
          mountPath: /var/run/webhook/serving-cert
      volumes:
      - name: serving-cert
        secret:
          secretName: admission-serving-cert
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: deepsea.kubecon.com
webhooks:
- name: deepsea.kubecon.com
  sideEffects: None
  failurePolicy: Fail
  admissionReviewVersions:
  - v1beta1
  rules:
  - apiGroups:
    - "deepsea.kubecon.com"
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - modules
  clientConfig:
    service:
      namespace: deepsea
      name: admission-webhook
      path: /validate/v1/modules
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUV6RENDQXJRQ0NRRFlxNDlWeVZoVGZqQU5CZ2txaGtpRzl3MEJBUXNGQURBb01TWXdKQVlEVlFRRERCMWgKWkcxcGMzTnBiMjR0ZDJWaWFHOXZheTVrWldWd2MyVmhMbk4yWXpBZUZ3MHhPVEV4TURNeE5ERXpNVEZhRncweQpNREV4TURJeE5ERXpNVEZhTUNneEpqQWtCZ05WQkFNTUhXRmtiV2x6YzJsdmJpMTNaV0pvYjI5ckxtUmxaWEJ6ClpXRXVjM1pqTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUF5bzUrUEVxeG1ybkwKTFhpVmZFcG9qRFJBNS85b0VxYU5kU1ZrRklnYnpvZndqbUZWTEpTQ2x4MmRycWtSWTFWWnBIWjBzSTNGcUNCYwpGRkdVVUNBSEpDK1IzU3V0ckVVOHEvRnpUSUZxNmhodUNEdE5XUEdTQW9hWDlYR2RZZGhWOWE3WGhBR3lnbHRCCklBS1lWK3pHc01NRjgzSDE1UUFRaVRmRStjYXNiMGxuUk9acDRlOTIyWDN2R2dMMUJidmUveWVCQThFZTQ2OTAKZ0JmL25Ga2VzTmlJbHg1aVA3WXBxa2UyWk5saFJ2c20rcXJqS3hoMi9OZEFvMjJYU0x5ZTN3Y0NYOGJYTnY2OQpIbEllOUs5RmxwUTM4ZHhickJ0ajltcG56dzZ3MEV1aDBmczVsb1FEWUxIS21tYXJiQnVFT3FYanJCbW1QdkYzCmtPY3c4aG45RUF6VklwQVhpMERMMG5iVDVOMU1HWTYyQ1MxaXUvWWdDSXJkamRWRTB2NGc4MWtXM3FqSHZDN2wKbktCeUZ4Tk9yV2JKbXAyMzhMOUc5YTZON2pyV3R4VENtdVBrSTBjQXlQKzRpL2N5QW1CODBMNWZtTU1BNHVCZgpLZkR3SkUrQm9WK2RtdXA5ZExGTUR4dFYzTGJrZ1BaRnZxQ1hiTDBvcEgrcEFZQTRGYlQ4NXhFdnMwdTc2K0pUCko3bERiMHVOTU83K21QK1RyWTVXaUFlS2wvTUtQdjNCVGwwalY5WlpsajEwU0Ficlgvalk4ZHhNYTdqZXVPckQKVlJxTFlTeEVJdjF3YjN6ZnhqalNySTkwSEx3R2tBdVBwdFVQWHpHVDJ3UkVydHNQV25sZEY3bXNjL1JqRVdmZgo3d3RKQTZhQUFmVzVMbytHUHM3ckRWUHdRaURGV1M4Q0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBZ0VBCldldWNMdUo3TXJROWRNcEZXOWNvWm5Cc3pkeFpEcUJKZFZqQTNDUEV3dmFUdjVpNlhLNnJkbzk5QnVTZWtBN0cKMzRFOFlBZ3NWVWpQQlRWUWNGajJOenZnaTM3RUZ3M0VYN1ZqaklIc2FsazFEald6Yk44UGwrY2ZNOTN2ZGw0SAozUzdlMUNzQzRPTnQyYlBiZzQxTUZwd0k5djdKN0Rpa1ExVzBlNjdZRlBhMzQxRFFrNjZBaWhxTUxZeUwzcE10CmIrdCttNmtFNzNHWUFwMm5EbmErekVZZVZmd1RyUmw1ZmZRSGRhOG9TWVNSQjdFSlk3S3BoRkJaNk0wcUhwT28KUk5zYVVTQXV5WDZhS0lTdkViVmt3NlR2dW52MzVxZmpWSmo5cnkxd212YVh3a0xyTWo4eU95Y044MjVmb3dzRQo3Z0owemJXczBJTTVKMllVSFJDNEpZTHcwS1k0YndWdnlqcUllUzQ4RW5DdkMzRFkzK0xiM01kTTRuOXNwQjVICndrVUhWejhhSVJqNzdEbVpyY21oU1doZGxKVmpuMkhDOUlNMHA2ZFkwMTZWSmhxUVF0WEw2N2tvdU5oQVJIRnEKNC9QWnBMODk0d2VtZk5GNnNRL3hIZE96U3NRbEtKQWF5WTk2WkRQeWMvVGRCdEtmckxwRDRKa0FRM21FY2YwcgpEOHpJZ1hmK2pBNXdWTGFSL3ZlaDFWTkVBY0NpbzloOTF6WEJjTXl5V0FDLzF4dXBwd2hOV3VQMjFhUjJ0cGVTCmNBNVZrd042RlA5cGhLSVF6VlU1V2dQWUJyVklLcXc5azFBV2I1RHRPMmxwYXJWeDMrYkFJRVB4SnJBWE1GeFQKTzQ4RVZkVjVLN2RUeUUxeU81QjMwbVRSUlFNWm9TMC9FcHcrRjlvSm5LMD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
