apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: devices.things.kubecon.io
spec:
  group: things.kubecon.io
  preserveUnknownFields: false
  versions:
  - name: v1alpha1
    served: true
    storage: true
  - name: v1
    served: true
    storage: false
  names:
    kind: Device
    plural: devices
    listKind: DeviceList
  scope: Namespaced
  conversion:
    strategy: Webhook
    webhookClientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUV6RENDQXJRQ0NRQ2ZuNjhmeUlCdWpqQU5CZ2txaGtpRzl3MEJBUXNGQURBb01TWXdKQVlEVlFRRERCMWoKYjI1MlpYSnphVzl1TFhkbFltaHZiMnN1ZEdocGJtZHpMbk4yWXpBZUZ3MHhPVEV4TURNeE1qUXpNamRhRncweQpNREV4TURJeE1qUXpNamRhTUNneEpqQWtCZ05WQkFNTUhXTnZiblpsY25OcGIyNHRkMlZpYUc5dmF5NTBhR2x1ClozTXVjM1pqTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUFuemJpSTNyMmJ2eDQKMnIzZ3BqS3lnNXVwVnFiSGsrUjVkRDlpbVdUZDNtVkl4bFJHbGhsSG1ZQk5MVWlFR0hvZjhmZnliVGo3enU3KwpMdVZNOExhZktaTmI2Z0Y4ZmIyYjdVRDNTNmtkRHdxL2F5NklLd1I2cVBKcng0MFNWUzlQN3V4Y3Z2SUloNGRKCkVBNmdBTjVHUnBaL08zMkJRMXZvd01wNTdwNG1Fb2JYTWF0MDVHOUlQWE4xQk05dFdURis2bzd0bHYvSEpxVm8KWnBhYmlJWVo3RWFaV24zZWpBTTVVWWJ5RTJ0LzJTSUJweVg2b0pSUmVaMmN6aEhBNkJ2dUN6N3NRZzJpMHE4eQpPcmloL1RTUlN0U05CcWZEN0pqdDFjMkQyRXNvMGFOZHNGK2ZzaGJTTjhCN2hocEszeENaOHpWUXV4MExzUlFECjJuanl2alhqQVdTRmJkZC8xaXk4TG1NeFpvVlNDOExIWW9JUXdqNTUyNERMYURjblVsKzBNUTVISWRCTU42UVoKck5JUHBnTVJVaFAvTS8vYTBEM0VLU24vQk10ZXY0YnRTQmhGUFJzeWdUbWsxc0lrUVB2WHlhK1hLdUVwTnZaQgpjdjg0RVI1WXVmREZVQ2ZDTFg5YTBNQXZjeXpDb0FNa3R0M2svbk1XR3NYZURwN3lVM25DNWxlNkw2ZDBIQTJyCmRUSnRwRWZwZk5BZXlQcmE1dUlNZzRFL0tNWCt1K24yQXBKUTJxTFhDbktkZjUzZ0E4K1NUWFBaK0lEa1ZSMWoKbWd4UVFaamNXd1lwdkxjdEpSWFByNjhWemtyTkhqR0FoU1BQdHFnVGtxVldWYzl6RkpaOFZYM1V1dnlzVjVKeQpGQ283R21Fd1J1djhCejNuendMUU42UlgzZEFZalpjQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBZ0VBCkNBdWUyUnM3TnpCeksySktoMXA2N3poV2dUTVN5T1JNRTc0YkduaklmbGlGL2lramx6dDFLYlAyU0hGYVkxTTYKZGZabnBTL3ZYbGU5Z0tKeTJTd0NVMVR3blZtd3hpVnd3S1RvUWZONVFGNGxNWU5wWlRDNWFhYk5PbzNEcmdqMQpBRVgxVHVjT3liTEx1Y3lVTllqZ3RjNmJuTytwYXFYemtBeVEyZ0pCMjFsZVQxT3RuemFVQUlidmdLZVdnMmF3CjZHRUNSSkVTT09PQ0w5OVNESm5jVGxteHQ4VytKU2prQ0g1Q2tmNjZ6NHhXN212OEVkQ095MEdmamgvVkhtTkoKbHZESDkwVFBxcHN4QW5xSDhOY2Z1U21UcUViQW9RbW9wZ2hBbGlhVlh5amVZMmNpenNyZ2NsK0ZqRnViTTdJcgpQeXZvVmsycGpuR1M1cit2MERjRzcwaXMwWG5KUnJVWTBlSk1WSFVFZzkrOHNTODE4TXZVS1FPcUNicHIvYmFuCnJMRWltMXVZS1RvN3ZZdTFRT1RzUmxBY0s0Z05pZ3c4dFlpODZLbDZSODVNc0pFbGY1azlxeTZ3djk5aFRmbmoKSGtueE1sclk5WXJQaG9rRnRSUkJJbGZDa2VKYW5EaW5XRXdxWkIxdWQ4K3duUlJ4dWhNQ2lVVlNBUCs2eXdjaApFZVBReklqcElOWDdXaVBWWWg5UXo1SjhXTnNHTC83SDVBY2Q2TDJ1OVRYUXFmSGp0bzRFRXJXV0ZvMURUVFUxCksrSGhqOGNjbCtWUnUvU1NGSFZvMVdzTXBmaVU0THdYYzBianFZWXY1VWdCWE40K2lnVDRWUUtxK0t0NGx6cFIKZVpMaFhEcXdJd2x5VndRbzdoT00xZUs0NE04d3g2MFhKaVY1L0hnN2pTYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        namespace: things
        name: conversion-webhook
        path: /convert/v1beta1/devices
  additionalPrinterColumns:
    - name: Pressure
      type: string
      JSONPath: .status.outputs[?(@.name=='pressure')].value
    - name: Pumps
      type: string
      JSONPath: .spec.inputs[?(@.name=='activeCount')].value
    - name: Alarm
      type: string
      JSONPath: .status.outputs[?(@.name=='alarm')].value
  validation:
    "openAPIV3Schema":
      description: Device is a specification for a device in a deep see station.
        It can be a sensor (if it only has outputs), or an actor (if it only has
        inputs), or both.
      type: object
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: DeviceSpec is the spec for a Sensor resource
          type: object
          properties:
            inputs:
              description: inputs are the desired value for an actor.
              type: array
              items:
                description: Value is a named and typed value.
                type: object
                required:
                  - name
                properties:
                  name:
                    description: name is the name of this input value.
                    type: string
                  type:
                    type: string
                  value:
                    description: value is the floating point input value.
                    type: string
                  boolean:
                    description: boolean is a true or false value.
                    type: boolean
                  float:
                    description: float is a floating point input value.
                    type: string
                  integer:
                    description: integer is a integer value.
                    type: integer
                    format: int32
        status:
          description: DeviceStatus is the status for a Sensor resource
          type: object
          properties:
            observedInputs:
              description: inputs are the desired value for an actor.
              type: array
              items:
                description: Value is a named and typed value.
                type: object
                required:
                  - name
                properties:
                  name:
                    description: name is the name of this input value.
                    type: string
                  type:
                    type: string
                  value:
                    description: value is the floating point input value.
                    type: string
                  boolean:
                    description: boolean is a true or false value.
                    type: boolean
                  float:
                    description: float is a floating point input value.
                    type: string
                  integer:
                    description: integer is a integer value.
                    type: integer
                    format: int32
            outputs:
              description: outputs are values of a sensor.
              type: array
              items:
                description: Value is a named and typed value.
                type: object
                required:
                  - name
                properties:
                  name:
                    description: name is the name of this input value.
                    type: string
                  type:
                    type: string
                  value:
                    description: value is the floating point input value.
                    type: string
                  boolean:
                    description: boolean is a true or false value.
                    type: boolean
                  float:
                    description: float is a floating point input value.
                    type: string
                  integer:
                    description: integer is a integer value.
                    type: integer
                    format: int32