steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/deepsea-admission-webhook', '.', '-f', 'Dockerfile-admission' ]
images:
  - 'gcr.io/$PROJECT_ID/deepsea-admission-webhook'