steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/deepsea-controllers', '.', '-f', 'Dockerfile-controllers' ]
images:
  - 'gcr.io/$PROJECT_ID/deepsea-controllers'