steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/things-conversion-webhook', '.', '-f', 'Dockerfile-conversion' ]
images:
  - 'gcr.io/$PROJECT_ID/things-conversion-webhook'