steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/deepsea-simulator', '.', '-f', 'Dockerfile-simulator' ]
images:
  - 'gcr.io/$PROJECT_ID/deepsea-simulator'