apiVersion: v1
kind: Namespace
metadata:
  name: things
spec: {}
---
apiVersion: v1
kind: Service
metadata:
  name: conversion-webhook
  namespace: things
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    webhook: "true"
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: conversion-webhook
  namespace: things
---
apiVersion: v1
kind: Secret
metadata:
  name: conversion-serving-cert
  namespace: things
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUV6RENDQXJRQ0NRQ2ZuNjhmeUlCdWpqQU5CZ2txaGtpRzl3MEJBUXNGQURBb01TWXdKQVlEVlFRRERCMWoKYjI1MlpYSnphVzl1TFhkbFltaHZiMnN1ZEdocGJtZHpMbk4yWXpBZUZ3MHhPVEV4TURNeE1qUXpNamRhRncweQpNREV4TURJeE1qUXpNamRhTUNneEpqQWtCZ05WQkFNTUhXTnZiblpsY25OcGIyNHRkMlZpYUc5dmF5NTBhR2x1ClozTXVjM1pqTUlJQ0lqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUFuemJpSTNyMmJ2eDQKMnIzZ3BqS3lnNXVwVnFiSGsrUjVkRDlpbVdUZDNtVkl4bFJHbGhsSG1ZQk5MVWlFR0hvZjhmZnliVGo3enU3KwpMdVZNOExhZktaTmI2Z0Y4ZmIyYjdVRDNTNmtkRHdxL2F5NklLd1I2cVBKcng0MFNWUzlQN3V4Y3Z2SUloNGRKCkVBNmdBTjVHUnBaL08zMkJRMXZvd01wNTdwNG1Fb2JYTWF0MDVHOUlQWE4xQk05dFdURis2bzd0bHYvSEpxVm8KWnBhYmlJWVo3RWFaV24zZWpBTTVVWWJ5RTJ0LzJTSUJweVg2b0pSUmVaMmN6aEhBNkJ2dUN6N3NRZzJpMHE4eQpPcmloL1RTUlN0U05CcWZEN0pqdDFjMkQyRXNvMGFOZHNGK2ZzaGJTTjhCN2hocEszeENaOHpWUXV4MExzUlFECjJuanl2alhqQVdTRmJkZC8xaXk4TG1NeFpvVlNDOExIWW9JUXdqNTUyNERMYURjblVsKzBNUTVISWRCTU42UVoKck5JUHBnTVJVaFAvTS8vYTBEM0VLU24vQk10ZXY0YnRTQmhGUFJzeWdUbWsxc0lrUVB2WHlhK1hLdUVwTnZaQgpjdjg0RVI1WXVmREZVQ2ZDTFg5YTBNQXZjeXpDb0FNa3R0M2svbk1XR3NYZURwN3lVM25DNWxlNkw2ZDBIQTJyCmRUSnRwRWZwZk5BZXlQcmE1dUlNZzRFL0tNWCt1K24yQXBKUTJxTFhDbktkZjUzZ0E4K1NUWFBaK0lEa1ZSMWoKbWd4UVFaamNXd1lwdkxjdEpSWFByNjhWemtyTkhqR0FoU1BQdHFnVGtxVldWYzl6RkpaOFZYM1V1dnlzVjVKeQpGQ283R21Fd1J1djhCejNuendMUU42UlgzZEFZalpjQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBZ0VBCkNBdWUyUnM3TnpCeksySktoMXA2N3poV2dUTVN5T1JNRTc0YkduaklmbGlGL2lramx6dDFLYlAyU0hGYVkxTTYKZGZabnBTL3ZYbGU5Z0tKeTJTd0NVMVR3blZtd3hpVnd3S1RvUWZONVFGNGxNWU5wWlRDNWFhYk5PbzNEcmdqMQpBRVgxVHVjT3liTEx1Y3lVTllqZ3RjNmJuTytwYXFYemtBeVEyZ0pCMjFsZVQxT3RuemFVQUlidmdLZVdnMmF3CjZHRUNSSkVTT09PQ0w5OVNESm5jVGxteHQ4VytKU2prQ0g1Q2tmNjZ6NHhXN212OEVkQ095MEdmamgvVkhtTkoKbHZESDkwVFBxcHN4QW5xSDhOY2Z1U21UcUViQW9RbW9wZ2hBbGlhVlh5amVZMmNpenNyZ2NsK0ZqRnViTTdJcgpQeXZvVmsycGpuR1M1cit2MERjRzcwaXMwWG5KUnJVWTBlSk1WSFVFZzkrOHNTODE4TXZVS1FPcUNicHIvYmFuCnJMRWltMXVZS1RvN3ZZdTFRT1RzUmxBY0s0Z05pZ3c4dFlpODZLbDZSODVNc0pFbGY1azlxeTZ3djk5aFRmbmoKSGtueE1sclk5WXJQaG9rRnRSUkJJbGZDa2VKYW5EaW5XRXdxWkIxdWQ4K3duUlJ4dWhNQ2lVVlNBUCs2eXdjaApFZVBReklqcElOWDdXaVBWWWg5UXo1SjhXTnNHTC83SDVBY2Q2TDJ1OVRYUXFmSGp0bzRFRXJXV0ZvMURUVFUxCksrSGhqOGNjbCtWUnUvU1NGSFZvMVdzTXBmaVU0THdYYzBianFZWXY1VWdCWE40K2lnVDRWUUtxK0t0NGx6cFIKZVpMaFhEcXdJd2x5VndRbzdoT00xZUs0NE04d3g2MFhKaVY1L0hnN2pTYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQ1N3d2dna29BZ0VBQW9JQ0FRQ2ZOdUlqZXZadS9IamEKdmVDbU1yS0RtNmxXcHNlVDVIbDBQMktaWk4zZVpVakdWRWFXR1VlWmdFMHRTSVFZZWgveDkvSnRPUHZPN3Y0dQo1VXp3dHA4cGsxdnFBWHg5dlp2dFFQZExxUjBQQ3I5ckxvZ3JCSHFvOG12SGpSSlZMMC91N0Z5KzhnaUhoMGtRCkRxQUEza1pHbG44N2ZZRkRXK2pBeW5udW5pWVNodGN4cTNUa2IwZzljM1VFejIxWk1YN3FqdTJXLzhjbXBXaG0KbHB1SWhobnNScGxhZmQ2TUF6bFJodklUYTMvWklnR25KZnFnbEZGNW5aek9FY0RvRys0TFB1eENEYUxTcnpJNgp1S0g5TkpGSzFJMEdwOFBzbU8zVnpZUFlTeWpSbzEyd1g1K3lGdEkzd0h1R0drcmZFSm56TlZDN0hRdXhGQVBhCmVQSytOZU1CWklWdDEzL1dMTHd1WXpGbWhWSUx3c2RpZ2hEQ1BubmJnTXRvTnlkU1g3UXhEa2NoMEV3M3BCbXMKMGcrbUF4RlNFLzh6LzlyUVBjUXBLZjhFeTE2L2h1MUlHRVU5R3pLQk9hVFd3aVJBKzlmSnI1Y3E0U2syOWtGeQovemdSSGxpNThNVlFKOEl0ZjFyUXdDOXpMTUtnQXlTMjNlVCtjeFlheGQ0T252SlRlY0xtVjdvdnAzUWNEYXQxCk1tMmtSK2w4MEI3SSt0cm00Z3lEZ1Q4b3hmNjc2ZllDa2xEYW90Y0tjcDEvbmVBRHo1Sk5jOW40Z09SVkhXT2EKREZCQm1OeGJCaW04dHkwbEZjK3ZyeFhPU3MwZU1ZQ0ZJOCsycUJPU3BWWlZ6M01VbG54VmZkUzYvS3hYa25JVQpLanNhWVRCRzYvd0hQZWZQQXRBM3BGZmQwQmlObHdJREFRQUJBb0lDQUZhQ0FxTldsM204Y29vZjYyVkNYSjZICndKM1ZadEZqcmQ1TTVtMEVVazBaYVU1aDBpeVNOY1lnNFU0K2ZZK3pJNUpjcjN0TEgvN1Mrb2RPamR5b3paaFEKZWZ1T3JTN0JERzBBQko0Mm1CUnBPWktxS05CKzBZcmtsVTFLeUhCQ2tjTDI2SG5UbG5EVlFBeWFkYk9qRWpvZQpZYWxZU3hqblluTUdVUFFuTi9hUEQzUHNma24wY1NMNmpkVjhReVRZY09aUG5LYVQrWWgxRFdIWWFVL24xVVA5CkpDdjRBaWkvUTdDWml3U2tQMFlpWlJXRjNFVE44ZXNMaVh5cVJzK1hCV05VNEJnUHdxMkpCZGpFSXpncUROdkUKMjQrSExqeHE1NmRvMEQrQXJ3QWhMTEc5YzA3WGVZZFRiWXB5MU1XWkJwMFFGZnBsRU1vNVh0S2hMdnZNMmJjMwpXWVlqanAvdk8vZWRmYytjZWd2SDdpSDl2QXh3SWVycHdGK2FJa3lXWjNENi83TGhuRit0S2hSMFdidk1UdDVmCmYvUURBRnVmUVNuRzRnVVBNRFRoOCtTS3lLQ1NHT09JbGZZUVZuenovaVNjUThxbVp1MHEzVkRobFRpeWY2REEKSmNpUnlMc0E1OWJaMU9PRzZhTVN0ODExOUZza2x0aHJUMm9xcVk3dGZzWGJRQm1nSjZER2g0QVV1QTZzeiswYgpFSTZRbWp5QVNuZWtDd0xXeWw2YlNVbVRwbzBrTVpQblBZQTZVL0lhUHZPRFJhL2VlQTQweTFYWFM3YzBRZU0vCi93WWpvdWpWUnlrYzMzSThmU2tMK2hUSUE4TnFMbUphVzlOMFBNUmgyNlphb2dGM2pSa2JMZmhYWU50YTlzWlIKSmwyM3NIc2Zjbkc5KzFGREZLaEpBb0lCQVFEVDdXQ0R6WGx3SCtKcGdBOFBsc0ZZSEZLTzVJakNVUllvMjVSbgpkd2drMEFRU3pVbzFkYWZRVTQ1UGhQSzRqNkNKUzArNTI2Lzc0VWJMcm9uYlhlVnUwUWJ0d3ZiM2NRcFd5ZlcvCnQyVHNwRVJ6WkFmU3dndGZzOStHVExsdjVDY0paMlRpYXN4QjR2dXIzcWp6Z1ArOENCeXBIMkV6Qko2aGhUaVoKdG11clQ1YlBBNi9QU29qRE55cmtTREVwbWgxSlRLY0FaTWlKM3VRTkx3RXV5bGZ1ZGZBeGVkQmpaL1BhbGwyYgpueG5yUmhpbzJ5bG9EN3E1MThNMWpieEIyS2VUNm5GVHhJR2RQeW1teUV0RCtacm5MNS83Q2hGVm5PS3AxbjFjClZHbXBadDYvU0FhQk4reGhLakRtWFJOVDB2RWpsSjVlRUhZMm5pdWJiQkI4QmVQN0FvSUJBUURBVXlzN3dGQWQKRVpNKzZFQ0FzcFV0WVlaTW9vSFNSTlI0MFhGOC9CK2kzbEJTUE1rRjNuZkdpSDBzbEVvbjdkSS8vMWlGNURnMQpGWGVaODBCTkMwRVNNQ2FUVnlvL1lXZXhKVFhsdHY0VFA0SDM1Ry84aHNxYmZSQjI0aytVelU3cXpLblVxNDF0CmNWWEdoZS9qcDBnSStmYXJDUldLVGRMaXU0RVlETk9Qc09CY05IUjRJSmkzc1N2UWRyd3RDVkNtK3dOZG1oQlMKWE1Va2hHWEhVZ2RiL0xub2xBZnk5dW02TjMyK2dGa1Y3blg3b3RDbUU3MnNxN3VzY0xSSkdIUFlKUmlaWHRmdgp0RE5pbmRtcjJlK202MGpxYzhQVlhhd2hnQXhUa25BZzNneEt1cWhabmt4WlQwZ2MxQnUrZGxaTE5xNm8wL3ZTCkFCTFZMKzZyUlc0VkFvSUJBQURvbnFaU0JqaEYycm1yRStWME53WUNzUlB0eE94WVhxajBNQkcxZi9Kd2RlUUMKdjFPMVdtL1pPOTM1YXZVQm9LV1dEaFIwN2E4OXl3anFpYXJJSDBpM1dybEFRY0RUMmtCL0F5KzhRSkdITHNmego0TmkxZmtqOXczS1c5NkNVTU5xb2Q5VkVzZldDWEtQakE0UnZ4Q2p4Ty9ZNXJUZ0R5QTVYUE9QajFWaFpzZ0xYCk9EVENWQTNLT2NQYXoyTW5Sd0xlY2tUZEtjTDFrcksveGRpR2c1UUJLM042MnpyaDRqakl0a1FKalpubHBndHIKVFNVbUZCM2gzL05sMVMzUEdRRFlXMzRKZEtqUThZUEdqaFFQaU90KzE4ZkN4a3BBcnZRZGVGSWlCb1gwYS9ZVAovL3NqMno2YmFMUkVKK1lQSEh1VGtvNUNzYzhRSkkyNUMrVU1QV3NDZ2dFQkFMa2IwNUxSQ01yUnJhMXdrUlROCnpiTStHS3NPQm5IQmVkZEhqem5DMlJoRGJYK1pyY29PVTY0c2xINGh4RFltT3FVS09jTzA0enlFaXZjTUg2bUgKMlh1T0NMTHJ4R2Y0Y25zWDI0WmIyTFBoL2svLytLRlBneGFoQ3dYQjBPTGhzTUZoZDF5UU9iRkswa29mZzhMVApzUXVpdXYzbjRtbVplZzVzZGxZVmtsTE01VVVaMzdmM2Q4WGxxc3djWEFYazMxRzRhNGJkMERQVndwSGhOS3poCmtOL0NvWlR2VmE5T1k2dXQyVU5QK1c2WWM4cGM3UUhNSWxWZGZXYjlteWgzZHBobExBWUNPVWduWXdYWjlEWHAKcnpZelk1ejFDMW9EckxjWnJjT0tRSTRCNmtiSzNWcFVlQnZGcVJ6R01tWGhOREYwVWl1QXpQRlV6TXVRTk9GNApFL2tDZ2dFQUorNjZCSHF2YnJhK3I5VmU0Nm55aC8rWmt1NVE1UkdpamRYbDQ2MTFJVlhvcmhQa3FGdERacUFzCkhYTWN6aUlmMmR3ZTFvY1JTK29oeDFDSFNHVStIdHdvMTZ2Z1dNYlpxZUJEVnUyYWdGVW54dTJQMnJCZ1AzbUoKb3FYaDZWRTc3MUtRZUcvU0hjMGJ2Njc5NUZ0eUJSVU9MM3ZjZXRHelA0VGRsWHdqTUdac3dQNTlIQXlONk5VdgpVcnZJSTVWVVI5ekJQdHhBM3dEOU55TzcxTEU3OFhWNHF2aWdzV0lZVEpKa0NCajZxdFV3NlFJUVRiZ3VhcXIwCnpaMEhuVkh2RXc0a1c2d2ZmVlhSWE54L3locldqUFVzUmFwanVvNDhnM2gzS2FnaTNRVWwrZ2VuT0pmd2I1RWgKNXBNbDVIcURtc0JYZFFFS29vYzFVT3loYUVwMERRPT0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversion-webhook
  namespace: things
  labels:
    webhook: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      webhook: "true"
  template:
    metadata:
      labels:
        webhook: "true"
    spec:
      serviceAccountName: conversion-webhook
      containers:
      - name: webhook
        image: docker.io/sttts/things-conversion-webhook@sha256:3e6f9d96254e462b1690fec716cc2b471915af8c759dfe5d91afd7fe9fd60c9e
        imagePullPolicy: IfNotPresent
        command: ["/conversion-webhook"]
        args:
        - --cert-dir=/tmp/certs
        - --secure-port=8443
        - --tls-cert-file=/var/run/webhook/serving-cert/tls.crt
        - --tls-private-key-file=/var/run/webhook/serving-cert/tls.key
        - --v=4
        volumeMounts:
        - name: serving-cert
          readOnly: true
          mountPath: /var/run/webhook/serving-cert
      volumes:
      - name: serving-cert
        secret:
          secretName: conversion-serving-cert
